Main/urls.py
from django.urls import path
from .import views

app_name = "Main"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('profile/',views.profile, name="profile"),
    path("logout/",views.logout_user, name="logout"),
    path("signin/",views.signin, name="signin"),
    path("signup/",views.signup, name="signup"),
    path("update/",views.update, name ="update"),
    path("delete/",views.delete, name ="delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from .import settings

from Main import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('Main/', include("Main.urls")),
    path('', views.index),
    path('intro/', include("intro.urls")),
    path('Service/', include("Service.urls")),
    path('product/', include('product.urls')),
    path('Board/', include('Board.urls')),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pic = models.ImageField(upload_to="user/%y/%m")
    age = models.IntegerField(default=1)
    comment = models.TextField()
    
    
    
    
    #product에서 사용
    
    productnum = models.TextField(blank=True)
    cardname = models.TextField(blank=True)
    cardnum = models.TextField(blank=True)
    Expiration = models.TextField(blank=True)
    CVV = models.TextField(blank=True)

    def getpic(self):
        if self.pic:
            return self.pic.url
        return "/media/user/noimage.png"
# Create your models here.

Main/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from .models import User
from django.contrib import messages


def index(req):
    return render(req,"Main/index.html")

def profile(req):
    return render(req,"Main/profile.html")

def logout_user(req):
    logout(req)
    return redirect("Main:index")

def signin(req):
    if req.method == "POST":
        un = req.POST.get("uname")
        up = req.POST.get("upass")
        u = authenticate(username=un, password=up)
        if u:
            login(req,u)
            messages.success(req,f"{u}님 환영합니다")
            return redirect("Main:index")
        else:
            messages.error(req,"계정 정보를 확인해주세요")
    
    return render(req,"Main/signin.html")

def signup(req):
    if req.method == "POST":
        un = req.POST.get("uname")
        up = req.POST.get("upass")
        uc = req.POST.get("ucomn")
        pi = req.FILES.get("upic")  
        User.objects.create_user(username=un, password=up, comment=uc, pic=pi)
        return redirect("Main:signin")
    return render(req,"Main/signup.html")

def update(req):
    if req.method == "POST":
        u = req.user
        up = req.POST.get("upass")
        um = req.POST.get("umail")
        pi = req.FILES.get("upic")
        uc = req.POST.get("ucomn")       
        if up:
            u.set_password(up)
        if pi:
            u.pic = pi
        u.comment = uc
        u.email = um
        u.save()
        login(req,u)
        return redirect("Main:profile")
    return render(req,"Main/update.html")

def delete(req):
    req.user.delete()
    return redirect("Main:index")
# Create your views here.

templates/Main/index.html
{% extends 'base.html' %}

{% block con %}

<!-------------------------------------------------------------------------------  Main Page Body 영역 ----------------------------------------------------------------------------------------------------------------------->

        <div class="a" style="display: flex; min-width: auto;">
            <div style="margin-left: 65px; width: 100%; height: auto; display: flex;  flex-direction: column;">
                
                <div class="row justify-content-md-center" style="padding-top: 100px;">
                

                    <div class="row text-center" style="padding-top: 20px; padding-left:500px; width: 1500px;">       
                        <img src="https://pbs.twimg.com/media/BgGB_jOCMAAgdwq.png" style="width: 500px; height:500px;">
                    </div>

                    <div style="width: 1500px; color: white; padding-top: 50px; padding-left:480px">
                        <h1>GOLD MOON Cloud Company </h1>
                    </div>
            
                </div>

                
                <div class="row justify-content-md-center" style="padding-top: 180px; padding-left: 10px;">
                    <div class="row" style="padding-top: 50px; padding-right:200px; width: 1500px; color:white;">       
                        <h1>🔹Services</h1><br><br><br>
                        <h3>다양한 산업과 규모에 맞춘 서비스를 제공합니다</h3>
                    </div>

                    <div style="padding-left: 10px; padding-top: 10px;">
                       
                        <div class="row">
                            <div class="col text-center" style="color: white;">
                                <img src="https://blog.intostudy.com/wp-content/uploads/2020/12/Computer_Science.jpg" style="width: 300px; height: 300px;">
                                <h1>Compute</h1>
                            </div>

                            <div class="col text-center" style="color: white;">
                                <img src="https://www.scs.gatech.edu/sites/scs.gatech.edu/files/images/mercury/artboard_3_copy.png" style="width: 300px; height: 300px;">
                                <h1>Security</h1>
                            </div>

                            <div class="col text-center" style="color: white;">
                                <img src="https://static.techspot.com/articles-info/2016/images/2020-05-10-image-2.jpg" style="width: 300px; height: 300px;">
                                <h1>Storage</h1>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col text-center" style="color: white; padding-left: 250px;">
                                <img src="https://www.scs.gatech.edu/sites/scs.gatech.edu/files/images/mercury/artboard_21_copy.png" style="width: 300px; height: 300px;">
                                <h1>DataBase</h1>
                            </div>

                            <div class="col text-center" style="color: white; padding-right: 250px;">
                                <img src="https://www.scs.gatech.edu/sites/scs.gatech.edu/files/images/mercury/artboard_11_copy.png" style="width: 300px; height: 300px;">
                                <h1>Network</h1>
                            </div>
                        </div>
                 
                        
                        
                    </div>
                </div>

                <div class="row justify-content-md-center" style="padding-top: 130px;">
                    <div class="row text-end" style="padding-top: 50px; width: 1250px; color: white;">
                        <h1>🔹Solution</h1>       
                        <img src="https://www.stisgroup.com/wp-content/uploads/2016/10/managed-services-slider2-1024x682.jpg" style="width: 1500px; height:500px; padding-top:10px">
                    </div>
                    <div class="text-center" style="width: 1500px; color: white; padding-right:100px; padding-top: 30px;">
                        <h3>클라우드 구조에 적합한 합리적인 가격의 세가지 솔루션을 제공</h3>
                    </div>
                </div>

                <div class="row justify-content-md-center" style="padding-top: 180px;">
                    <div class="row" style="padding-top: 50px; width: 1250px; color:white">
                        <h1>🔹Communications</h1>       
                        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEVuWgKm0qTxndxAYdDZCzAZNwnQvIfGgsGw&usqp=CAU" style="width: 1250px; height:400px;">
                    </div>
                    <div class="text-center" style="width: 1500px; color: white; padding-top: 10px;">
                        <br>
                        <h3>다양한 클라이언트와의 소통을 통한 더 나은 환경을 제공</h3>
                    </div>
                </div>

                <div class="row" style="padding-top: 180px; padding-left: 600px;">
                    <div style="color: white; width: 500px; height:500px;">
                        <div class="d-flex justify-content-around" style="padding-top: 40px;">
                            <h1>Offer</h1>
                            <div class="p-2" style="font-size:12px">
                                Python<br><br>
                                React<br><br>
                                Django<br><br>
                                Java Script<br><br>
                                CSS<br><br>
                            </div>
                            <div class="p-2" style="font-size:12px">
                                AWS EC2<br><br>
                                AWS S3<br><br>
                                AWS Lambda<br><br>
                            </div>
                            <div class="p-2" style="font-size:12px">
                                Ubuntu<br><br>
                                Redhat<br><br>
                                Cent OS<br><br>
                            </div>
                        </div>
                        <div class="mt-5 mb-5 text-center">
                            <span class="material-symbols-outlined">
                                browse_activity
                            </span><br>
                                Made by Hoon 2022.DEC
                        </div>
                    </div>
                </div>

         

            </div>

        </div>

{% endblock %}

{% block noauth %}

<div class="a" style="display: flex; min-width: auto;">
    <div style="margin-left: 65px; width: 100%; height: auto; display: flex;  flex-direction: column;">
        
        <div class="row justify-content-md-center" style="padding-top: 100px;">
        

            <div class="row text-center" style="padding-top: 20px; padding-left:500px; width: 1500px;">       
                <img src="https://pbs.twimg.com/media/BgGB_jOCMAAgdwq.png" style="width: 500px; height:500px;">
            </div>

            <div style="width: 1500px; color: white; padding-top: 50px; padding-left:480px">
                <h1>GOLD MOON Cloud Company </h1>
            </div>
    
        </div>

        
        <div class="row justify-content-md-center" style="padding-top: 180px; padding-left: 10px;">
            <div class="row" style="padding-top: 50px; padding-right:200px; width: 1500px; color:white;">       
                <h1>🔹Services</h1><br><br><br>
                <h3>다양한 산업과 규모에 맞춘 서비스를 제공합니다</h3>
            </div>

            <div style="padding-left: 10px; padding-top: 10px;">
               
                <div class="row">
                    <div class="col text-center" style="color: white;">
                        <img src="https://blog.intostudy.com/wp-content/uploads/2020/12/Computer_Science.jpg" style="width: 300px; height: 300px;">
                        <h1>Compute</h1>
                    </div>

                    <div class="col text-center" style="color: white;">
                        <img src="https://www.scs.gatech.edu/sites/scs.gatech.edu/files/images/mercury/artboard_3_copy.png" style="width: 300px; height: 300px;">
                        <h1>Security</h1>
                    </div>

                    <div class="col text-center" style="color: white;">
                        <img src="https://static.techspot.com/articles-info/2016/images/2020-05-10-image-2.jpg" style="width: 300px; height: 300px;">
                        <h1>Storage</h1>
                    </div>

                </div>

                <div class="row">
                    <div class="col text-center" style="color: white; padding-left: 250px;">
                        <img src="https://www.scs.gatech.edu/sites/scs.gatech.edu/files/images/mercury/artboard_21_copy.png" style="width: 300px; height: 300px;">
                        <h1>DataBase</h1>
                    </div>

                    <div class="col text-center" style="color: white; padding-right: 250px;">
                        <img src="https://www.scs.gatech.edu/sites/scs.gatech.edu/files/images/mercury/artboard_11_copy.png" style="width: 300px; height: 300px;">
                        <h1>Network</h1>
                    </div>
                </div>
         
                
                
            </div>
        </div>

        <div class="row justify-content-md-center" style="padding-top: 130px;">
            <div class="row text-end" style="padding-top: 50px; width: 1250px; color: white;">
                <h1>🔹Solution</h1>       
                <img src="https://www.stisgroup.com/wp-content/uploads/2016/10/managed-services-slider2-1024x682.jpg" style="width: 1500px; height:500px; padding-top:10px">
            </div>
            <div class="text-center" style="width: 1500px; color: white; padding-right:100px; padding-top: 30px;">
                <h3>클라우드 구조에 적합한 합리적인 가격의 세가지 솔루션을 제공</h3>
            </div>
        </div>

        <div class="row justify-content-md-center" style="padding-top: 180px;">
            <div class="row" style="padding-top: 50px; width: 1250px; color:white">
                <h1>🔹Communications</h1>       
                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEVuWgKm0qTxndxAYdDZCzAZNwnQvIfGgsGw&usqp=CAU" style="width: 1250px; height:400px;">
            </div>
            <div class="text-center" style="width: 1500px; color: white; padding-top: 10px;">
                <br>
                <h3>다양한 클라이언트와의 소통을 통한 더 나은 환경을 제공</h3>
            </div>
        </div>

        <div class="row" style="padding-top: 180px; padding-left: 600px;">
            <div style="color: white; width: 500px; height:500px;">
                <div class="d-flex justify-content-around" style="padding-top: 40px;">
                    <h1>Offer</h1>
                    <div class="p-2" style="font-size:12px">
                        Python<br><br>
                        React<br><br>
                        Django<br><br>
                        Java Script<br><br>
                        CSS<br><br>
                    </div>
                    <div class="p-2" style="font-size:12px">
                        AWS EC2<br><br>
                        AWS S3<br><br>
                        AWS Lambda<br><br>
                    </div>
                    <div class="p-2" style="font-size:12px">
                        Ubuntu<br><br>
                        Redhat<br><br>
                        Cent OS<br><br>
                    </div>
                </div>
                <div class="mt-5 mb-5 text-center">
                    <span class="material-symbols-outlined">
                        browse_activity
                    </span><br>
                        Made by Hoon 2022.DEC
                </div>
            </div>
        </div>

 

    </div>

</div>

{% endblock %}

templates/Main/profile.html
{% extends 'base.html' %}

{% block con %}

<body>
    <div class="a" style="display: flex; font-size: 20px; font-weight: bold; color: white; padding-top: 50px; padding-left: 500px; height: 840px;">
        <div>
            <h1>{{user}}'s Profile</h1>
            <hr>
            <img src ="{{ user.getpic }}" class="rounded-circle" height="250px">
        </div>
        <div style="padding-left: 150px; padding-top: 20px;">
            <div class="mb-3 mt-5">
                <label class="form-label">USERNAME</label><br>
                <input type ="text" value ="{{user}}" disabled><br>
            </div>
            <div class="mb-3">
                <label class="form-label">PASSWORD</label><br>
                <input type ="text" value ="{{ user.pass }}" disabled><br>
            </div>
            <div class="mb-3">
                <label class="form-label">Email</label><br>
                <input type ="text" value ="{{user.email}}" disabled><br>
            </div>
            <div class="mb-3">
                <label class="form-label">Comment</label><br>
                <textarea class="form-control" disabled style="font-weight: bold; height: 100px">{{ user.comment }}</textarea>
            </div>
            <div class ="text-end">
                <a href ="{% url 'Main:update' %}"><button class="btn btn-outline-light">UPDATE</button></a>
                <a href ="{% url 'Main:delete' %}"><button class="btn btn-outline-danger">계정삭제</button></a>
            </div>

        </div>
    </div>
</body>
{% endblock%}

templates/Main/signin.html
{% extends 'base.html' %}

{% block noauth %}

<body>
    <div class="a" style="display: flex; justify-content: center; padding-left: 150px; padding-top: 80px; height: 840px; color: white;">
        <div style="width: 500px;">
            <form method="post">
                {% csrf_token %}
                <h1><b>로그인</b></h1>
                <div class="mt-5">
                    <input type="text" name="uname" class="form-control" placeholder="INPUT USERNAME" style="font-weight: bold; width: 400px;">
                    <input type="password" name="upass" class="form-control mt-4" placeholder="INPUT PASSWORD" style="font-weight: bold; width: 400px;"><br><br>
                    <button class="btn btn-outline-light">LOGIN</button>
                </div>
            </form>
        </div>
        <div style="width: 600px;">
            <img src="https://thumbs.gfycat.com/YellowishInbornGonolek-size_restricted.gif" width="500px" height="500px">
        </div>
    </div>
</body>
{% endblock%}


<!-- https://images.squarespace-cdn.com/content/v1/59ee7776b1ffb6f51e078009/1630712814874-4DMYCUQCKCGGP9TYUTDV/login-gif-12.gif -->

templates/Main/signup.html
{% extends 'base.html' %}

{% block noauth %}

<body>
    <div class="a" style="display: flex; justify-content: center; padding-left: 80px; padding-top: 80px; height: 840px; color: white;">
        <div style="width: 500px;">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <h1><b>회원가입</b></h1>
                <div class="mb-3 mt-5">
                    <label class="form-label">ID</label><br>
                    <input type="text" name="uname" placeholder="아이디입력"><br><br>
                    <label class="form-label">Password</label><br>
                    <input type="password" name="upass" placeholder="비밀번호 입력"><br><br>
                    <label class="form-label">Commnet</label><br>
                    <textarea class="form-control" name="ucomn" placeholder="자기소개" style="width: 600px; height: 200px;"></textarea><br>
                    <label class="form-label">Profile Photo</label><br>
                    <input type="file" class="form-control" name ="upic" id="exampleInputPassword1" style="width: 600px;"><br>
                    <button class="btn btn-outline-light">회원가입</button>
                    <a href="{% url 'Main:index' %}"><button type="button" class ="btn btn-outline-light">뒤로가기</button></a>
                </div>
            </form>
        </div>
        <div style="padding-left: 150px; width: 600px;">
            <img src="https://i.pinimg.com/originals/79/42/b8/7942b89ebd6bb6e9047c3651a99bdb4d.gif" width="500px" height="500px">
        </div>
    </div>
</body>
{% endblock%}

templates/Main/update.html
{% extends 'base.html' %}

{% block con %}

<body>
    <div class="a" style="display: flex; font-size: 20px; font-weight: bold; color: white; padding-top: 50px; padding-left: 500px; height: 840px;">
        <div>
            <h1>{{user}}'s Update</h1><br>
            <img src="https://media.tenor.com/E7HT0L0wlAgAAAAC/update-beat.gif" width="500px" height="630px padding-bottom:50px;">
        </div>
        <div style="padding-left: 100px; padding-top: 20px;">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3 mt-5">
                    <label class="form-label">USERNAME</label><br>
                    <input type ="text" value ="{{user}}" disabled>
                </div>
                <div class="mb-3 mt-5">
                    <label class="form-label">Password</label><br>
                    <input type ="password" name="upass">
                </div>
                <div class="mb-3 mt-5">
                    <label class="form-label">Email</label><br>
                    <input type ="text" value ="{{user.email}}" name="umail">
                </div>
                <div class="mb-3 mt-5">
                    <label class="form-label">Commnet</label><br>
                    <textarea class="form-control" name="ucomn" placeholder="자기소개"></textarea>
                </div>
                <div class="mb-3 mt-5">
                    <label class="form-label">Profile Photo</label><br>
                    <input type="file" class="form-control" name="upic">
                </div>
                <div class="text-end">
                    <button class = "btn btn-outline-success">Save</button>
                    <a href="{% url 'Main:profile' %}"><button type="button" class ="btn btn-outline-light">뒤로가기</button></a>
                </div>
            </form>
        </div>

    </div>
</body>

{% endblock%}