Main/urls.py
from django.urls import path
from .import views

app_name = "Main"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('profile/',views.profile, name="profile"),
    path("logout/",views.logout_user, name="logout"),
    path("signin/",views.signin, name="signin"),
    path("signup/",views.signup, name="signup"),
    path("update/",views.update, name ="update"),
    path("delete/",views.delete, name ="delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from .import settings

from Main import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('Main/', include("Main.urls")),
    path('', views.index),
    path('intro/', include("intro.urls")),
    path('Service/', include("Service.urls")),
    path('product/', include('product.urls')),
    path('Board/', include('Board.urls')),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views


app_name = 'product'
urlpatterns = [

    path('index/', views.product, name='index'),
    path('purchase/', views.purchase, name='purchase'),
    path('product_check/', views.product_check, name='product_check'),
    path('product_cancel/', views.product_cancel, name='product_cancel'),

    

    
]

product/models.py
from django.db import models

product/views.py
from django.shortcuts import render,redirect



def product(request):
    #인덱스를 실행시킬 때 


   return render(request, 'product/index.html')


def purchase(request):

   if request.method == "POST": 
      u = request.user
      up = request.POST.get("productnum")
      ucnum = request.POST.get("cardnum")
      ucname = request.POST.get("cardname")
      ucexp = request.POST.get("cardexp")
      ucvv = request.POST.get("cardCVV")
      u.productnum = up
      u.cardname = ucname
      u.cardnum = ucnum
      u.Expiration = ucexp
      u.CVV = ucvv
      u.save()
      return redirect('product:index')

   return render(request, 'product/purchase.html')

def product_check(request):


   return render(request, 'product/product_check.html')

def product_cancel(request):
   u = request.user
   u.productnum = ""
   u.save()
   return redirect('Main:index')

templates/product/index.html
{% extends 'base.html' %}

{% block con %}






  
  {% comment %} <div class="container py-3"> {% endcomment %}
    {% comment %} <header> {% endcomment %}

      <div class="a" style="display: flex; justify-content: center; height: 800px; weight: 1200px;">
        <div class="center">
          <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 style="color:white;" class="display-4 fw-normal">Plan 선택</h1>
            <h3 style="color:white;">Plan 결제가 확인되면, 전화를 통해 상세한 Plan 설정에 대한 상담 및 추가결제가 이뤄집니다. </h3>
          </div>
    {% comment %} </header> {% endcomment %}
      
            <main>
              <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
                <div class="col">
                  <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                      <h4 class="my-0 fw-normal">소매업용 Plan</h4>
                    </div>
                    <div class="card-body">
                      <h1 class="card-title pricing-card-title">$10</h1>
                      <ul class="list-unstyled mt-3 mb-4">
                        <li>디스커버리 솔루션</li>
                        <li>디지털 상거래</li>
                        <li>소매업을 위한 API 관리</li>
                        <li>데이터 웨어하우스 현대화</li>
                        <li>Looker를 통한 소매 분석</li>
                        <li>소매업체 고객 데이터 플랫폼</li>
                        <li>Google Cloud 기반 SAP</li>
                        <li>소매업을 위한 Anthos</li>
                      </ul>
                      
                    </div>
                  </div>
                </div>
                <div class="col">
                  <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                      <h4 class="my-0 fw-normal">미디어 및 엔터테인먼트용 Plan</h4>
                    </div>
                    <div class="card-body">
                      <h1 class="card-title pricing-card-title">$15</h1>
                      <ul class="list-unstyled mt-3 mb-4">
                        <li>가상 포스트 프로덕션</li>
                        <li>원격 생산성 및 공동작업</li>
                        <li>데이터 웨어하우스 현대화</li>
                        <li>시청자 통계</li>
                        <li>AI로 보강된 동영상 콘텐츠</li>
                        <li>인프라 현대화</li>
                        <li>아카이브 마이그레이션</li>
                        <li>동영상 처리</li>
                      </ul>
                    
                    </div>
                  </div>
                </div>
                <div class="col">
                  <div class="card mb-4 rounded-3 shadow-sm ">
                    <div class="card-header py-3 text-bg-primary `">
                      <h4 class="my-0 fw-normal">제조업용 Plan</h4>
                    </div>
                    <div class="card-body">
                      <h1 class="card-title pricing-card-title">$29</h1>
                      <ul class="list-unstyled mt-3 mb-4">
                        <li>고객 데이터 플랫폼</li>
                        <li>고급 마케팅 분석</li>
                        <li>전자상거래 마이그레이션 및 현대화</li>
                        <li>지능형 제품</li>
                        <li>프로덕션 품질관리</li>
                        <li>제조업을 위한 공동작업</li>
                        <li>제조업을 위한 하이브리드 클라우드</li>
                        <li>제품 탐색 및 검색</li>
                      </ul>
                      
                    </div>
                  </div>
                </div>
              </div>

          {% if user.is_anonymous %}
          <p style="color:white; font-size:50px;">Plan을 구매하실려면 로그인을 먼저해주세요 </p>
          <a href="{% url 'Main:signin' %}" class=" btn btn-lg btn-outline-primary">로그인하러 가기</a>
          {% else %}
            {% if user.productnum %}
            <a href="#" class=" doublepurchase w-100 btn btn-lg btn-outline-primary">Plan을 구매하러가기!</a>
            {% else %}
            <a href="{% url 'product:purchase' %}" class="w-100 btn btn-lg btn-outline-primary">Plan을 구매하러가기!</a>
            {% endif %}
          {% endif %}

            
          </div>
        
      </div>
      
      
          
        </body>
        <script type='text/javascript'>


          $(document).ready(function() {
            $(".doublepurchase").on('click', function() {
            
                alert("현재 {{user.productnum}} 구매진행중입니다, 다른 Plan을 원하실 경우 취소 후 재구매해주세요.")
      
              
            });
          });
        </script>
    </div>

{% endblock%}




{% block noauth %}



<div class="a" style="display: flex; justify-content: center; height: 800px; weight: 1200px;">
  <div class="center">
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 style="color:white;" class="display-4 fw-normal">Plan 선택</h1>
      <h3 style="color:white;">Plan 결제가 확인되면, 전화를 통해 상세한 Plan 설정에 대한 상담 및 추가결제가 이뤄집니다. </h3>
    </div>
{% comment %} </header> {% endcomment %}

      <main>
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
          <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
              <div class="card-header py-3">
                <h4 class="my-0 fw-normal">소매업용 Plan</h4>
              </div>
              <div class="card-body">
                <h1 class="card-title pricing-card-title">$10</h1>
                <ul class="list-unstyled mt-3 mb-4">
                  <li>디스커버리 솔루션</li>
                  <li>디지털 상거래</li>
                  <li>소매업을 위한 API 관리</li>
                  <li>데이터 웨어하우스 현대화</li>
                  <li>Looker를 통한 소매 분석</li>
                  <li>소매업체 고객 데이터 플랫폼</li>
                  <li>Google Cloud 기반 SAP</li>
                  <li>소매업을 위한 Anthos</li>
                </ul>
                
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
              <div class="card-header py-3">
                <h4 class="my-0 fw-normal">미디어 및 엔터테인먼트용 Plan</h4>
              </div>
              <div class="card-body">
                <h1 class="card-title pricing-card-title">$15</h1>
                <ul class="list-unstyled mt-3 mb-4">
                  <li>가상 포스트 프로덕션</li>
                  <li>원격 생산성 및 공동작업</li>
                  <li>데이터 웨어하우스 현대화</li>
                  <li>시청자 통계</li>
                  <li>AI로 보강된 동영상 콘텐츠</li>
                  <li>인프라 현대화</li>
                  <li>아카이브 마이그레이션</li>
                  <li>동영상 처리</li>
                </ul>
              
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm ">
              <div class="card-header py-3 text-bg-primary `">
                <h4 class="my-0 fw-normal">제조업용 Plan</h4>
              </div>
              <div class="card-body">
                <h1 class="card-title pricing-card-title">$29</h1>
                <ul class="list-unstyled mt-3 mb-4">
                  <li>고객 데이터 플랫폼</li>
                  <li>고급 마케팅 분석</li>
                  <li>전자상거래 마이그레이션 및 현대화</li>
                  <li>지능형 제품</li>
                  <li>프로덕션 품질관리</li>
                  <li>제조업을 위한 공동작업</li>
                  <li>제조업을 위한 하이브리드 클라우드</li>
                  <li>제품 탐색 및 검색</li>
                </ul>
                
              </div>
            </div>
          </div>
        </div>

    {% if user.is_anonymous %}
    <p style="color:white; font-size:50px;">Plan을 구매하실려면 로그인을 먼저해주세요 </p>
    <a href="{% url 'Main:signin' %}" class=" btn btn-lg btn-outline-primary">로그인하러 가기</a>
    {% else %}
      {% if user.productnum %}
      <a href="#" class=" doublepurchase w-100 btn btn-lg btn-outline-primary">Plan을 구매하러가기!</a>
      {% else %}
      <a href="{% url 'product:purchase' %}" class="w-100 btn btn-lg btn-outline-primary">Plan을 구매하러가기!</a>
      {% endif %}
    {% endif %}
  
  
       
    </body>
    <script type='text/javascript'>


      $(document).ready(function() {
        $(".doublepurchase").on('click', function() {
         
            alert("현재 {{user.productnum}} 구매진행중입니다, 다른 Plan을 원하실 경우 취소 후 재구매해주세요.")
   
          
        });
      });
    </script>
  



{% endblock %}

templates/product/product_check.html
{% extends 'base.html' %}

{% block con %}
<body>
  <div class="a" style="display: flex; justify-content: center; height: 900px; ">
  <div class="center">
    
    <main>



      {% if user.productnum %}


      <div class="container py-4">
        <br><br><br>
          <header class="pb-3 mb-4 border-bottom">
              <span class="fs-4">구매확인 및 환불</span>
          </header>
      
          <div class="p-5 mb-4 bg-light rounded-3">
            <div class="container-fluid py-5">
              <h1 class="display-5 fw-bold">현재 구매 중인 솔루션</h1>
              <p class="col-md-8 fs-4">현재 {{ user }} 고객님은 {{ user.productnum }}을 구매진행중입니다.</p>



                <a href="#" class="delete btn btn-outline-dark" data-uri2="{% url 'product:product_cancel' %}">구매취소</a>
                

            </div>
          </div>

      
      
          </div>
      

    {% else %}


    <div>
      <header class="pb-3 mb-4 border-bottom">
          <span class="fs-4"><p style="color:white; font-size:50px;">구매확인 및 환불 </p></span>
        </a>
      </header>

      <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
          <h1 class="display-5 fw-bold">현재 {{ user }} 고객님이 구매중인 솔루션이 없습니다. </h1>

        </div>
      </div>



      </div>


    
      {% endif %}

      <footer class="pt-3 mt-4 text-muted border-top">
        <div class="row align-items-md-stretch">
            <div class="col-md-6">
              <div class="h-100 p-5 text-bg-dark rounded-3">
                <h2>환불절차</h2>
                <p>환불을 신청하면 진행중이던 솔루션이 중단될 수 있습니다.

                  <br><br>전액 환불의 경우 환불 절차가 완료 혹은 취소될 때까지 솔루션은 계속 중단됩니다.
                  <br><br>카드 환불에서 카드 중 '!' 표시가 있는 건은 결제일 이후 6~18개월이 경과된 카드 결제 건입니다. 해당 건 중 카드사, PG사에 따라 자동으로 취소가 되지 않을 경우 취소가 완료될 때까지 솔루션이 중단됩니다.
                  <br><br>카드 환불 중 통신 장애나 카드사, PG사의 사정에 따라 바로 취소가 안 되는 경우 솔루션이 중단됩니다.
                  <br><br>카드 환불 중 차액 결제가 필요한 경우 차액 결제가 완료될 때까지 솔루션이 중단됩니다.</p>

              </div>
            </div>
      </footer>
    </div>





    {% comment %} 



    {% endcomment %}









    </main>


  </div>
  </div>
</body>
  <script type='text/javascript'>


   $(document).ready(function() {
     $(".delete").on('click', function() {
      if(confirm("정말로 취소하시겠습니까?")) {
         location.href = $(this).data('uri2');

       }
     });
   });
 </script>
  {% endblock%}


  {% block noauth %}
  <div class="a" style="display: flex; justify-content: center; height: 800px; ">
    <div class="center">
      <p style="color:white; font-size:50px;"><br>로그인을 먼저해주세요 </p>
      <div style="position:absolute; margin-left:154px;"><a href="{% url 'Main:signin' %}" class=" btn btn-lg btn-outline-primary">로그인하러 가기</a></div>
    </div>
  </div>
  {% endblock %}

templates/product/purchase.html
{% extends 'base.html' %}

{% block con %}

  <body class="bg-light">
    
   <div class="container">
     <main>
       <div class="py-5 text-center">
         
         <h2>제품 구매</h2>
         <p class="lead"></p>
       </div>
   
       <div class="row g-5">
         
         <div class="col-md-7 col-lg-8">
           





          <form id = "purchase" method="post">
          {% csrf_token %}
             
   
 
             
   
             <h4 class="mb-3"> 구매 제품 선택 </h4>
   
             <div class="my-3">
               <div class="form-check">
                 <input id="credit" name="productnum" value="소매업용 Plan" type="radio" class="form-check-input" checked required>
                 <label class="form-check-label" for="credit">소매업용 Plan</label>
               </div>
               <div class="form-check">
                 <input id="debit" name="productnum" value="미디어 및 엔터테인먼트용 Plan" type="radio" class="form-check-input" required>
                 <label class="form-check-label" for="debit">미디어 및 엔터테인먼트용 Plan</label>
               </div>
               <div class="form-check">
                 <input id="paypal" name="productnum" value="제조업용 Plan" type="radio" class="form-check-input" required>
                 <label class="form-check-label" for="paypal">제조업용 Plan</label>
               </div>
             </div>
   
             <div class="row gy-3">
               <div class="col-md-6">
                 <label for="cardname" class="form-label">카드명</label>
                 <input type="text" name="cardname" class="form-control" id="cardname" placeholder="" required>
                 <small class="text-muted">카드명을 입력</small>
                 <div class="invalid-feedback">
                   Name on card is required
                 </div>
               </div>
   
               <div class="col-md-6">
                 <label for="cc-number" class="form-label">카드번호</label>
                 <input type="text" name="cardnum" class="form-control" id="cc-number" placeholder="" required>
                 <div class="invalid-feedback">
                   Credit card number is required
                 </div>
               </div>
   
               <div class="col-md-3">
                 <label for="cc-expiration" class="form-label">유효기간</label>
                 <input type="text" name="cardexp" class="form-control" id="cc-expiration" placeholder="" required>
                 <div class="invalid-feedback">
                   Expiration date required
                 </div>
               </div>
   
               <div class="col-md-3">
                 <label for="cc-cvv" class="form-label">CVV</label>
                 <input type="text" name="cardCVV" class="form-control" id="cc-cvv" placeholder="" required>
                 <div class="invalid-feedback">
                   Security code required
                 </div>
               </div>




             </div>
   
             <hr class="my-4">
   
             
             <a class="btn" href="#" onclick="purchase()" >제출하기</a>

           </form>





         </div>
       </div>
     </main>
   

   </div>
   
   

     </body>


<script>
function purchase() {

if(document.getElementById("cardname").value==''){
	alert("카드명을 입력해주십시오.");
	return false;
}
if(document.getElementById("cc-number").value==''){
	alert("카드번호를 입력해주십시오.");
	return false;
}
if(document.getElementById("cc-expiration").value==''){
	alert("유효기간를 입력해주십시오.");
	return false;
}
if(document.getElementById("cc-cvv").value==''){
	alert("CVV값 세자리를 입력해주십시오.");
	return false;
}




document.getElementById('purchase').submit();
alert("정상적으로 구매되었습니다.");

}
</script>


     {% endblock%}