Board/urls.py
from django.urls import path
from Board import views

app_name='Board'

urlpatterns = [
    path('', views.BoardList.as_view(), name='list'),
    path('<int:pk>/', views.BoardDetail.as_view(), name='detail'),
    path('create_board/', views.BoardCreate.as_view(),name='board_create'),
    path('delete_board/<int:pk>/', views.BoardDelete,name='board_delete'),
    path('update_board/<int:pk>/', views.BoardUpdate.as_view(),name='board_update'),
]

Main/urls.py
from django.urls import path
from .import views

app_name = "Main"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('profile/',views.profile, name="profile"),
    path("logout/",views.logout_user, name="logout"),
    path("signin/",views.signin, name="signin"),
    path("signup/",views.signup, name="signup"),
    path("update/",views.update, name ="update"),
    path("delete/",views.delete, name ="delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from .import settings

from Main import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('Main/', include("Main.urls")),
    path('', views.index),
    path('intro/', include("intro.urls")),
    path('Service/', include("Service.urls")),
    path('product/', include('product.urls')),
    path('Board/', include('Board.urls')),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Board/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from Main.models import User
import os

# Create your models here.
class Board(models.Model):
  title = models.CharField(max_length=30)
  content = models.TextField()
  file_upload = models.FileField(upload_to='board/data/%Y/%m/%d/', blank=True)
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  create_date = models.DateTimeField(auto_now_add=True)
  modify_date = models.DateTimeField(auto_now=True, null=True, blank=True)

  def __str__(self):
    return f'[PK:{self.pk}]-{self.title} :: {self.author}'

  def get_FileName(self):
    return os.path.basename(self.file_upload.name)

  def get_absolute_url(self):
    return f'/Board/{self.pk}/'

Board/forms.py
from django import forms
from .models import Board
from django.utils.safestring import mark_safe

class CustomFileWidget(forms.FileInput):
  def __init__(self, attrs={}):
      super().__init__(attrs)

  def render(self, name, value, attrs=None, renderer=None):
    print(value, name)
    output = []
    if value and hasattr(value, "url"):
      file_name = value.url.split('/')[-1]
      output.append(super().render(name, value, attrs))
      output.append(f'<span class="form-control">첨부파일 : <a class="text-reset text-decoration-none" target="_blank" href="{value.url}">{file_name}</a><input class="form-check-input ms-2 me-1" type="checkbox" name="upload_clear" id="upload_clear_id" value="upload_del">Delete</span>')
      return mark_safe(u''.join(output))
    output.append(super().render(name, value, attrs))
    return mark_safe(u''.join(output))

class BoardUpdateForm(forms.ModelForm):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.fields['title'].widget.attrs.update({'class': 'form-control'})
    self.fields['file_upload'].widget.attrs.update({'class': 'form-control'})
    self.fields['content'].widget.attrs.update({'class': 'form-control', 'rows':'20'})
  
  
  class Meta:
    model = Board
    fields = ('title', 'file_upload', 'content')
    widgets = {
      'file_upload': CustomFileWidget,
    }







class BoardCreateForm(forms.ModelForm):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.fields['title'].widget.attrs.update({'class': 'form-control'})
    self.fields['file_upload'].widget.attrs.update({'class': 'form-control'})
    self.fields['content'].widget.attrs.update({'class': 'form-control', 'rows':'20'})
  
  class Meta:
    model = Board
    fields = ('title', 'file_upload', 'content')

Board/views.py
from django.shortcuts import get_object_or_404, render, redirect
from Board.models import Board
from Board.forms import BoardCreateForm, BoardUpdateForm
from django.views.generic import DetailView, ListView, CreateView, UpdateView

from django.contrib.auth.decorators import login_required
from config import settings
import os

from django.core.exceptions import PermissionDenied
class BoardUpdate(UpdateView):
    model = Board
    form_class = BoardUpdateForm
    template_name = 'Board/board_form_update.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super().dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self, form):
        if self.get_object().file_upload.name != '':
            if self.object.file_upload != self.get_object().file_upload.name:
                file_upload_path=os.path.join(settings.MEDIA_ROOT, self.get_object().file_upload.path)
                if os.path.exists(file_upload_path):
                    os.remove(file_upload_path)
            if 'upload_clear' in self.request.POST:
                file_upload_path=os.path.join(settings.MEDIA_ROOT, self.get_object().file_upload.path)
                if os.path.exists(file_upload_path):
                    os.remove(file_upload_path)
                    self.object.file_upload = ''
        return super().form_valid(form)


class BoardList(ListView):
    model = Board
    template_name = 'Board/board_list.html'
    ordering = '-pk'
    paginate_by = 10

class BoardDetail(DetailView):
    model = Board
    template_name = 'Board/board_detail.html'

class BoardCreate(CreateView):
    model = Board
    form_class = BoardCreateForm
    template_name = 'Board/board_form.html'
    
    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            return super().form_valid(form)
        else:
            return redirect('/Board')

@login_required(login_url='Main:signin')
def BoardDelete(request, pk):
    board = get_object_or_404(Board, pk=pk)
    if request.user != board.author:
        return redirect('Board:detail', pk=pk)
    if board.file_upload:
        file_upload_path = os.path.join(settings.MEDIA_ROOT, board.file_upload.path)
        if os.path.exists(file_upload_path):
            os.remove(file_upload_path)
    board.delete()
    return redirect('Board:list')

templates/Board/board_detail.html
{% extends "base.html" %}
{% block con %}
<body>
  <div class="a" style="justify-content: center; height: 800px; ">
    <div class="center">
      <section class="board_detail-block">
        <div class="container mt-3">
        <div class="card border-dark mb-3">

          <div class="card">
            <h4 class="pt-1">{{ object.title }}</h4>
            {% if object.modify_date %}
              <p class="pt-1">Created by {{ object.author }} on {{ object.modify_date }}</p>
            {% else %}
              <p class="pt-1">Created by {{ object.author }} on {{ object.create_date }}</p>
            {% endif %}
          </div>
          
          <div class="card">
            {% if object.file_upload %}
            <a href="{{ object.file_upload.url }}" class="text-decoration-none text-muted" role="button" download>
              첨부파일 : <i class="fa-solid fa-file-lines me-2"></i>{{object.get_FileName}}
            </a>
            {% else %}
            <a class="text-decoration-none text-muted">첨부파일 : </a>
            {% endif %}
          </div>

          <div class="card-body text-dark">
            <p class="card-text">{{ object.content | linebreaksbr }}</p>
            <div class="mt-4"></div>
          </div>
          
          <div class="card-footer d-flex justify-content-between">
            <a href="/Board/" class="btn btn-outline-dark">목록</a>
            {% if user == object.author %}
            <span>
              <a href="{% url 'Board:board_update' object.id %}" class="btn btn-outline-dark">수정</a>
              <a href="{% url 'Board:board_delete' object.id %}" class="delete btn btn-outline-dark">삭제</a>
            </span>
            {% else %}
            <span>
              <a href="#" class="user_check btn btn-outline-dark">수정</a>
              <a href="#" class="user_check btn btn-outline-dark">삭제</a>
            </span>
            {% endif %}
          </div>

          
        </div>
        </div>
      </section>
    </div>
  </div>
</body>
{% endblock %}

templates/Board/board_form.html
{% extends "base.html" %}
{% block con %}
<body>
  <div class="a" style="justify-content: center; height: 800px; ">
    <div class="center">
      <section class="board_form-block">
      <div class="container mt-3">

        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="card">
            <div class="card-header input-group">
              <span class="input-group-text">제목 입력</span>
              {{ form.title }}
            </div>
            <div class="card-header input-group">
              {{ form.file_upload }}
            </div>
            <div class="card-body">
              {{ form.content }}
            </div>
            <button type="submit" class="btn btn-outline-dark">게시글 등록</button>
          </div>
        </form>

      </div>
      </section>
    </div>
  </div>
</body>
{% endblock %}

templates/Board/board_form_update.html
{% extends "base.html" %}
{% block con %}
<body>
  <div class="a" style="justify-content: center; height: 800px; ">
    <div class="center">
      <section class="board_form-block">
      <div class="container mt-3">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="card">
            <div class="card-header input-group">
              <span class="input-group-text">제목 입력</span>
              {{ form.title }}
            </div>
            <div class="card-header input-group">
              {{ form.file_upload }}
            </div>
            <div class="card-body">
              {{ form.content }}
            </div>
            <button type="submit" class="btn btn-outline-dark">게시글 수정</button>
          </div>
        </form>
        
      </div>
      </section>
    </div>
  </div>
</body>
{% endblock %}

templates/Board/board_list.html
{% extends "base.html" %}
{% block con %}
<!-- Board 영역 -->
<body>
  <div class="a" style="display: flex; justify-content: center; height: 800px; ">
    <div class="center">
      <div class="a" style="dispaly:block; height:800px; background:snow;">
          <div class="a" style="dispaly:block; weight:1000px; background:#B950FA; color: snow;">
    {% comment %} <div class= "container">
      <tr class = "text-center">  {% endcomment %}
              <br><h2 class="text-center mt-8">문의사항</h2>
              <h4 class="text-center mt-8">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;고객 지원이 필요할 경우 여기에 글을 작성해 주세요&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h4><br>
            </tr>
            </div>

          <div class="container">
            <table class="table table-striped">
              <!-- Table Head 영역 -->
              <thead class="thead-dark">
                <tr class="text-center">
                  <th>번호</th>
                  <th style="width:50%">제목</th>
                  <th>글쓴이</th>
                  <th>작성일</th>
                </tr>
              </thead>

              <!-- Table Body 영역 -->
              <tbody>
                {% for board in object_list %}
                <tr class="text-center">
                  <td>{{ board.id }}</td>
                  {% if user.is_authenticated %}
                    <td><a class="text-reset text-decoration-none" href="{{ board.get_absolute_url }}">
                    {{ board.title }}</a></td>
                  {% else %}
                    <td><a class="login_check text-reset text-decoration-none">
                    {{ board.title }}</a></td>
                  {% endif %}
                  <td>{{ board.author }}</td>
                  {% if object.modify_date %}
                  <td>{{ board.modify_date }}</td>
                  {% else %}
                  <td>{{ board.create_date }}</td>
                  {% endif %}
                </tr>
                {% endfor %}
              </tbody>
              
              </table>
              <div style="margin-left:950px;">
                <button type="button" class="btn btn-outline-dark" >
                  <a href="{% url 'Board:board_create' %}">
                    글 작성</a>
                </button>
              </div>

            {% if page_obj.paginator.count >= page_obj.paginator.per_page %}
            <!-- pagination 영역 -->
            <ul class="pagination justify-content-center">
              {% if page_obj.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">이전</a>
              </li>
              {% else %}
              <li class="page-item disalbed"><a class="page-link" href="#">이전</a></li>
              {% endif %}
              
              {% for page_number in page_obj.paginator.page_range %}
              {% if page_number >= page_obj.number|add:-3 and page_number <= page_obj.number|add:3 %}
                {% if page_number == page_obj.number %}
                  <li class="page-item active">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                  </li>
                {% else %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                  </li>
                {% endif %}
              {% endif %}
              {% endfor %}

              {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">다음</a>
              </li>
              {% else %}
              <li class="page-item disabled"><a class="page-link" href="#">다음</a></li>
              {% endif %}
            </ul>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
{% endblock %}

{% block noauth %}
<!-- Board 영역 -->
<body>
  <div class="a" style="display: flex; justify-content: center; height: 800px; ">
    <div class="center">
      <div class="a" style="dispaly:block; height:800px; background:snow;">
          <div class="a" style="dispaly:block; weight:1000px; background:#B950FA; color: snow;">
    {% comment %} <div class= "container">
      <tr class = "text-center">  {% endcomment %}
              <br><h2 class="text-center mt-8">문의사항</h2>
              <h4 class="text-center mt-8">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;고객 지원이 필요할 경우 여기에 글을 작성해 주세요&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h4><br>
            </tr>
            </div>
       
          <div class="container">
            <table class="table table-striped">
              <!-- Table Head 영역 -->
              <thead class="thead-dark">
                <tr class="text-center">
                  <th>번호</th>
                  <th style="width:50%">제목</th>
                  <th>글쓴이</th>
                  <th>작성일</th>
                </tr>
              </thead>

              <!-- Table Body 영역 -->
              <tbody>
                {% for board in object_list %}
                <tr class="text-center">
                  <td>{{ board.id }}</td>
                  {% if user.is_authenticated %}
                    <td><a class="text-reset text-decoration-none" href="{{ board.get_absolute_url }}">
                    {{ board.title }}</a></td>
                  {% else %}
                    <td><a class="login_check text-reset text-decoration-none">
                    {{ board.title }}</a></td>
                  {% endif %}
                  <td>{{ board.author }}</td>
                  {% if object.modify_date %}
                  <td>{{ board.modify_date }}</td>
                  {% else %}
                  <td>{{ board.create_date }}</td>
                  {% endif %}
                </tr>
                {% endfor %}
              </tbody>
              
              </table><br>

            {% if page_obj.paginator.count >= page_obj.paginator.per_page %}
            <!-- pagination 영역 -->
            <ul class="pagination justify-content-center">
              {% if page_obj.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">이전</a>
              </li>
              {% else %}
              <li class="page-item disalbed"><a class="page-link" href="#">이전</a></li>
              {% endif %}
              
              {% for page_number in page_obj.paginator.page_range %}
              {% if page_number >= page_obj.number|add:-3 and page_number <= page_obj.number|add:3 %}
                {% if page_number == page_obj.number %}
                  <li class="page-item active">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                  </li>
                {% else %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                  </li>
                {% endif %}
              {% endif %}
              {% endfor %}

              {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">다음</a>
              </li>
              {% else %}
              <li class="page-item disalbed"><a class="page-link" href="#">다음</a></li>
              {% endif %}
            </ul>
            {% endif %}

          </div>
        </div>
      </div>
    </div>
  </div>
</body>
{% endblock %}